### PR TITLE
Increase icon-size and font size of navbar contents

### LINKED ISSUE #123: Podman logo in navbar too small
I tried to fix this but it broke other things, so a TODO for me. Has something to do with docusaurus default styles i think.

### PR DESCRIPTION
**Pull request by cgiradkar**
Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>

closes #123

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar could you post a picture of the change too please?  The code LGTM, but I'm not 100% sure I'm looking at the right thing.

**Comment by cgiradkar** [comment]
Before: image
After: image
fyi @TomSweeneyRedHat @mairin

**Comment by TomSweeneyRedHat** [comment]
LGTM
Thanks @cgiradkar

**Comment by mairin** [comment]
this looks awesome @cgiradkar! Is it possible to upscale the logotype
"podman" text as well?

~m

**Comment by cgiradkar** [comment]
> this looks awesome @cgiradkar! Is it possible to upscale the logotype "podman" text as well? 

I have increased font-size for "podman" text to xxx-large
image

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@mairin want to merge this?

**Pull request merged**
