### PR TITLE
Add CLI installation to Downloads dropdown

### PR DESCRIPTION
**Pull request by ashley-cui**
Add link for CLI as well as Desktop installation
List desktop as first option for Mac and Windows
List CLI as first option for Linux

Fixes: https://github.com/containers/podman.io/issues/116

Linux

Windows

Mac

### CODE REVIEW

**Comment by ashley-cui** [comment]
@containers/podman-maintainers @mairin PTAL

**Comment by ashley-cui** [comment]
Decided to make the secondary font slightly smaller, but I'm not confident on that design choice.

**Comment by afbjorklund** [comment]
What is the "hat" platform ?

**Comment by rhatdan** [comment]
LGTM

**Comment by mairin** [comment]
@afbjorklund Podman Desktop supports deployments to OpenShift including OpenShift Developer Sandbox and OpenShift Local so it's a bit of a nod to that

**Comment by mairin** [comment]
This looks really good @ashley-cui thank you for doing this!!

**Pull request merged**
