### PR TITLE
Add dark mode to Community Meetings Section

### PR DESCRIPTION
**Pull request by cgiradkar**
Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@mairin @TomSweeneyRedHat PTAL

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Forgot this repo needs the smash hammer, smashing!

**Pull request merged**
