### PR TITLE
gitignore: exclude .yarn directory

### LINKED ISSUE #107: repository size is huge
Cloning this repository took a long time. The repo already takes 196 MB disk space right now on my system.

The problem seems to be that the `.yarn` directory is committed with all the packages.

The upstream docs show which files can/should be ignored: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Looks like the directory is not ignore since https://github.com/containers/podman.io/commit/35edaacad6372b7df569c31001b00a9ac6083335, given how big this grow in in just 5-6 weeks I say we really need to ignore this directory. It is not reasonable to expect contributors to pull such big repos.

### PR DESCRIPTION
**Pull request by Luap99**
Based on the docs[1] we can ignore these directories. The cache directory is already very big and I can only imagine how the size will grow in the future.

[1] https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Fixes #107

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Needs a rebase and I'm not familiar enough with Yarn to test this.  Will ask @mairin and others to comment.

**Comment by ashley-cui** [comment]
I wonder if this is necessary because we're deploying directly from this repo.. Might need to edit our deploy action?

**Comment by mairin** [comment]
@TomSweeneyRedHat other yarn projects I work with ignore this I think

**Comment by Luap99** [comment]
The github action should now check the build on the PR so we should be good to go if this passes.
This is the action install and according to the docs it should just pull it from the servers somewhere when it is not found
https://github.com/containers/podman.io/blob/e1c042832f52b43079b724e554a9232c7282de51/.github/workflows/setup_and_build.yml#L29-L30

Reading the upstream docs we likely want `--immutable` added instead of the  `--immutable-cache`, I will add another commit.

**Comment by TomSweeneyRedHat** [comment]
I'm fine with merging this; however, given it's size, I'd like to wait until after summit and merge this on Friday May 19.  If others are braver, feel free to over-rule and press the merge button.

**Comment by TomSweeneyRedHat** [comment]
Sorry, I was off by a week. Summit is next week, let's merge this next Friday or later.  It will need a rebase, but I'd hold off until Thurs.

**Comment by Luap99** [comment]
Tests are green let's get this in please.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 thanks for putting this together.  Time for the merge hammer.

**Pull request merged**
