### PR TITLE
Adding videos for Podman Desktop on Features Page

### PR DESCRIPTION
**Pull request by mairin**
Will address https://github.com/containers/podman.io/issues/49

Includes commits from https://github.com/containers/podman.io/pull/65 because I need them and I am not very good at git 😬 😂

### CODE REVIEW

**Comment by mairin** [comment]
OK! This is working and ready for review! You go to the features page, scroll down to where the videos are... as long as a video is fully in view in the browser pane, it will autoplay, and if it's scrolled out of the pane it will auto pause.

**Comment by TomSweeneyRedHat** [comment]
Very nice @mairin !  As a bonus, I finally figured out how to run yarn in my sandbox on my VM and then attach to the webserver spun up by yarn.

However, it looks like you need to rebase:

In your sandbox:  

git fetch --all
git rebase upstream/main

If you don't have upstream defined:

git remote add upstream https://github.com/containers/podman.io.git

Then do your git push command again, but use `--force` at the end.

**Comment by TomSweeneyRedHat** [comment]
And forgot to add that the changes LGTM

**Comment by mairin** [comment]
Thanks for the review, @TomSweeneyRedHat !!! :seal: :wave:

**Comment by mairin** [comment]
(This fixes https://github.com/containers/podman.io/issues/49)

**Pull request merged**
