### PR TITLE
Add Motorola Solutions logo

### PR DESCRIPTION
**Pull request by mairin**
Adding Motorola Solution's logo to recognize their contributions to the Podman community, with permission. Will need to renew permission to use by Aug 1, 2024.

Attaching screenshots of logo placement at various responsive breakpoints / light/dark modes:

Screenshot from 2023-07-19 16-04-03
Screenshot from 2023-07-19 16-03-53
Screenshot from 2023-07-19 16-03-41
Screenshot from 2023-07-19 16-03-35
Screenshot from 2023-07-19 16-03-14
Screenshot from 2023-07-19 16-03-01

### CODE REVIEW

**Comment by mairin** [comment]
(I want to wait to merge this until the Motorola Solutions folks have a chance to review.)

**Comment by TomSweeneyRedHat** [comment]
I'm headed out soon, LGTM pending Motorola approval

**Comment by mairin** [comment]
@TomSweeneyRedHat We have Motorola approval. I can merge this now and re-order in another PR?

**Comment by mairin** [comment]
(re-ordering to alpha order is tricky bc the logos have different aspect ratios :( )

**Pull request merged**
