### PR TITLE
Docs: Mention netavark / cni-plugins for debian/ubuntu

### PR DESCRIPTION
**Pull request by lsm5**
Continuing PR #201 from Scott Martin <smartin015@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Thanks [smartin015@gmail.com](mailto:smartin015@gmail.com)!

**Comment by lsm5** [comment]
@smartin015 PTAL

**Comment by lsm5** [comment]
Trivial enough change. Merging..

**Pull request merged**
