### PR TITLE
Touch up meeting room and desktop post

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Update the community meeting room location and the latest Podman Desktop version (1.4) blog post.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Addresses: #210  @afbjorklund thanks for the eagle eye and report!

**Review by cgiradkar — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar PTAL and merge if it LGTY

**Comment by cgiradkar** [comment]
> @cgiradkar PTAL and merge if it LGTY

@TomSweeneyRedHat Unfortunately i don't have merge rights :(

**Pull request merged**
