### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by fulldecent**
Following the convention in this file, `code typeset` is used for commands run in a shell environment.

The macOS Terminal app does not meet this definition, so fixing the typesetting for it.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@fulldecent Thanks for the commit, but our CI requires a signature.

Could you please `git commit --amend -s`, git fetch, git rebase, git push?  Looks like the same issue on your other commit too.

Thanks again,

**Comment by rhatdan** [comment]
The signature did not work?

**Comment by fulldecent** [comment]
Is the other one right?

**Comment by TomSweeneyRedHat** [comment]
@fulldecent still doesn't look like it's finding your signature.  Did you do a `git commit --amend -s`, then fetch, rebase and push?

**Comment by TomSweeneyRedHat** [comment]
Oh, now I comprehend your question @fulldecent .  Yes, your other PR was right, I just merged that thanks!

**Comment by TomSweeneyRedHat** [comment]
I think this was fixed in the other PR, so I'm going to close this one.  @fulldecent please correct me and reopen if I'm wrong.

**Pull request closed without merging**
