### PR TITLE
Add RSS Feed link in the footer

### LINKED ISSUE #148: Add blog RSS feed link
Apparently it's available at [https://blog.podman.io/feed/](https://blog.podman.io/feed/) but there's no link mentioning this anywhere.  Maybe include this in the page footer?

### PR DESCRIPTION
**Pull request by cgiradkar**
A RSS feed is  linked in the footer.

closes #148 

Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>

### CODE REVIEW

**Comment by cgiradkar** [comment]
needs #198 to be merged for this to work.

**Comment by mairin** [comment]
I have the same concern with this as expressed here: https://github.com/containers/podman.io/issues/125#issuecomment-1708176357

This RSS feed is only going to have old blog posts, right? Not new ones? So, following the RSS wouldn't actually do anything bc no new posts would be made? 

Unless the new blog posts are going to be included in docusaurus via api call or something?

**Comment by TomSweeneyRedHat** [comment]
That's a good point.  The rss feed, if possible, should send out notes when new blog posts are created.  It should ignore the older ones that were on the prior site.

**Review by cevich — APPROVED** [review]
I know less than nothing about JavaScript, heck I can barely spell the name.  Neverthelesss, I took a look at the test-build artifact's `index.html` (is that the right place?). A ctrl-f finds:

```
<a href="https://blog.podman.io/feed/" target="_blank" rel="noopener noreferrer" class="footer__link-item">RSS Feed<svg width="13.5" height="13.5" aria-hidden="true" viewBox="0 0 24 24" class="iconExternalLink_nPIU"><path fill="currentColor" d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z"></path></svg></a>
```

So I'm assuming that's correct?

LGTM - with big caveats (above)

**Comment by cgiradkar** [comment]
> I know less than nothing about JavaScript, heck I can barely spell the name. Neverthelesss, I took a look at the test-build artifact's `index.html` (is that the right place?). A ctrl-f finds:
> 
> ```
> <a href="https://blog.podman.io/feed/" target="_blank" rel="noopener noreferrer" class="footer__link-item">RSS Feed<svg width="13.5" height="13.5" aria-hidden="true" viewBox="0 0 24 24" class="iconExternalLink_nPIU"><path fill="currentColor" d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z"></path></svg></a>
> ```
> 
> So I'm assuming that's correct?
> 
> LGTM - with big caveats (above)

How Docusaurus generates a website is by using a configuration (JSON) and parsing the config to build a static website. What you found is in the build directory and hence a very good way to know "if it really compiled". It is correct!

**Comment by cevich** [comment]
Yay! I guessed right.

It's a bit of a chore (and maybe specialized knowledge) to go digging into the GHA logs, download the artifact zip, load it into browser, and enter the magic "developer mode".

Are you aware of a way to make this easier for other reviewers like me?  For example, can it put the site up somewhere temporarily on a PR-by-PR basis for reviewers to look at?

If it helps, we have access to the entirety of both GCP and AWS services.  For example, I'm imagining a workflow addition that uploads the built content to a GCS or S3 bucket and drops a link in the workflow output.  Could something like that work?

**Comment by cgiradkar** [comment]
> Yay! I guessed right.
> 
> It's a bit of a chore (and maybe specialized knowledge) to go digging into the GHA logs, download the artifact zip, load it into browser, and enter the magic "developer mode".
> 
> Are you aware of a way to make this easier for other reviewers like me? For example, can it put the site up somewhere temporarily on a PR-by-PR basis for reviewers to look at?
> 
> If it helps, we have access to the entirety of both GCP and AWS services. For example, I'm imagining a workflow addition that uploads the built content to a GCS or S3 bucket and drops a link in the workflow output. Could something like that work?

Someone else must know much more than me in this domain, but here is a blog which could be helpful: [Deploy Pull Requests for Review into Kubernetes with GitHub Actions](https://pumpingco.de/blog/review-pull-requests-by-deploying-them-into-kubernetes-with-github-actions/)
If anyone has more clarity about the matter, please reach out.

**Review by Luap99 — APPROVED** [review]
LGTM,
as I read this https://blog.podman.io/feed will only ever contain our new blogs from the wordpress site so it should just work like that.

**Comment by Luap99** [comment]
@cevich As for publishing a PR preview somewhere I agree that it would be helpful.  Currently I clone the PR code and build it locally to see the final result.

**Comment by cevich** [comment]
> Currently I clone the PR code and build it locally to see the final result.

Eek!  The current GHA workflow for PRs does a built and stores it as an artifact.  Maybe I should make the availability of that more obvious somehow?

An idea I just had was...what if we crafted a container image which, when provided a PR number, sucks down the latest artifact and serves it locally?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
