### PR TITLE
GHA: Add test-build workflow for PRs

### PR DESCRIPTION
**Pull request by cevich**
Implement a test workflow that reuses the setup_and_build workflow.

Depends on: https://github.com/containers/podman.io/pull/101

### CODE REVIEW

**Comment by cevich** [comment]
According to the status page, github-actions is currently broken.  This PR will need to be re-pushed and tested later.

**Comment by TomSweeneyRedHat** [comment]
This is probably Tom-education time, but how will renovate be useful in this repo?  Do we have packages in here that need watching/updating?

**Comment by Luap99** [comment]
> This is probably Tom-education time, but how will renovate be useful in this repo? Do we have packages in here that need watching/updating?

Welcome to the JS ecosystem, our site has 1262 dependencies at the moment if I can trust this command:
```
yarn info --name-only -R | wc -l
1262
```

**Comment by cevich** [comment]
@TomSweeneyRedHat Paul's comment is correct, there are a TON.  But I need to get some kind of CI in place first, otherwise zero checking would happen on the renovate PRs.  This is complicated by the fact there are multiple specifications for which node version to use (github-actions and `package.json`?).

**Comment by cevich** [comment]
Cool, so despite the outage continuing today, the workflows seem to be working.  Merging this manually so I can configure the repo. to require the new check on PRs.

**Pull request merged**
