### PR TITLE
Add Sept 2023 Cabal Notes

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Notes from the September 2023 Podman Community Cabal Meeting

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar PTAL.  Is there anything that needs to happen to update the community meeting where it shows the latest meetings?  I don't think that's auto-generated.

**Comment by cgiradkar** [comment]
You also need to add the file entry in the [index.ts](https://github.com/containers/podman.io/blob/main/static/data/meetings/notes/index.ts) as:
`import * as F20230720 from '@site/static/data/meetings/notes/2023-09-21/index.md';`
which then needs to be exported as: `export { F20230921 };`

**Comment by TomSweeneyRedHat** [comment]
Nice catch @cgiradkar .  I've updated index.ts

**Review by cgiradkar — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Merging!

**Pull request merged**
